# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-20 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_course_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='url',
            field=models.CharField(default='', max_length=120, verbose_name='\u8def\u5f84'),
        ),
    ]
